apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-upgrad1
  region: us-east-1

vpc:	
  id: "vpc-0c87e097d8c0661e1"
  subnets:
    private:
      private-a:
          az: "us-east-1a"
          id: "subnet-032f4291f85b9a764"
      private-b:
          az: "us-east-1b"
          id: "subnet-060fe3c5c37ee3fc1"
    public:
      public-a:
          az: "us-east-1a"
          id: "subnet-0bd781b0608f04cd3"
      public-b:
          az: "us-east-1b"
          id: "subnet-0095b94acc3099e33"
  clusterEndpoints:
    publicAccess: true
    privateAccess: true
  nat:
    gateway: Disable


iam:
  withOIDC: true
  serviceAccounts:
  - metadata:
      name: aws-load-balancer-controller
      namespace: kube-system
    wellKnownPolicies:
      awsLoadBalancerController: true
  - metadata:
      name: cluster-autoscaler
      namespace: kube-system
      labels: {aws-usage: "cluster-ops"}
    wellKnownPolicies:
      autoScaler: true
  - metadata:
      name: ebs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      ebsCSIController: true
  - metadata:
      name: efs-csi-controller-sa
      namespace: kube-system
    wellKnownPolicies:
      efsCSIController: true
  - metadata:
      name: external-dns
      namespace: kube-system
    wellKnownPolicies:
      externalDNS: true
  - metadata:
      name: cert-manager
      namespace: cert-manager
    wellKnownPolicies:
      certManager: true
 
nodeGroups:
  - name: ng-1
    labels: { role: workers }
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/cluster-upgrad: "shared"
    instancesDistribution:
      instanceTypes:
        - t2.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    privateNetworking: true
    subnets:
      - private-a
  - name: ng-2
    labels: { role: workers }
    tags:
      # EC2 tags required for cluster-autoscaler auto-discovery
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/cluster-upgrad: "owned"
    instancesDistribution:
      instanceTypes:
        - t2.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 1
    subnets:
      - public-a
